### ISSUE TITLE
It seems like the script is not working correctly in Sonoma 14.6

### ISSUE THREAD

**Issue by qnblackcat** [tech-otaku/menu-bar-clock#14]
Hi, I'm using a MBA M2 on Sonoma 14.6. Region is set to US.

I want to use the **"d MMM h:mm"** format. The script ran successfully as you can see in my image below. However, the date and time format in the menu bar wasn't change at all (it's still _Oct 2_, instead of _2 Oct_)

![CleanShot 02-10at 19 22](https://github.com/user-attachments/assets/f5e35cc0-af8d-4a20-a168-c2644e483528)

![CleanShot 02-10at 19 23](https://github.com/user-attachments/assets/07d4ac9f-e12e-4c4d-8203-70cd5a50b732)

**Comment by tech-otaku** [comment]
@qnblackcat 

> ...the date and time format in the menu bar wasn't change at all (it's still Oct 2, instead of 2 Oct)

This is due to a combination of your **Region** and  **Primary Preferred Language** settings in Settings > General > Language & Region and is not something the script has any control over.  

Unfortunately, the message the script displays on successful  execution can be misleading as it uses `date +'%-d %b'` which will always display the decimal day of the month before the abbreviated month name - 2 Oct - regardless of your settings.

Regards, Steve.

**Comment by qnblackcat** [comment]
I see. Thank you for your explanation
