### ISSUE TITLE
Adding Year

### ISSUE THREAD

**Issue by thectb** [tech-otaku/menu-bar-clock#4]
Thank you for setting this up it's awesome and easy.  Sadly, I don't know the first thing about how to do any of this but wanted to see if something was possible and if so How I can add this:  I want to add the year to the date.  The reason is because I want to show it in a screeen video presentation for a case I have in the Superior Court of California Van Nuys [shift-cmd-5].  I don't want to touch anything you have done.  Thank you.  Chris Barone.

**Comment by tech-otaku** [comment]
Chris,

Unfortunately it's not possible for the script to set the format of the menu bar clock to display the year as it simply mimics what can otherwise be achieved by setting the format through System Preferences. It is therefore limited to the formats defined by Apple. 

There are applications that allow you to customise the display of the menu bar clock, but I don't know if any will do what you're asking. [iClock](https://plumamazing.com/product/iclock/) and [iStat Menus](https://bjango.com/mac/istatmenus/) are two that I'm aware of.

**Comment by thectb** [comment]
Steve,

Thank you very much.  I really appreciate what you do and helping me.  I will try those out but either way, thank you.  Very kind.
 
 
Sincerely,
Chris Barone
 

    On Friday, January 1, 2021, 11:06:20 PM PST, Steve Ward <notifications@github.com> wrote:  
 
 


Chris,

Unfortunately it's not possible for the script to set the format of the menu bar clock to display the year as it simply mimics what can otherwise be achieved by setting the format through System Preferences. It is therefore limited to the formats defined by Apple.

There are applications that allow you to customise the display of the menu bar clock, but I don't know if any will do what you're asking. iClock and iStat Menus are two that I'm aware of.
