### ISSUE TITLE
Display week number

### ISSUE THREAD

**Issue by bramchi** [tech-otaku/menu-bar-clock#5]
I would give my firstborn to be able to display the week number in the menu bar clock. Can this be done?
If so, do let me know where to send my firstborn.

Love this script! MacOS should support these kind of customisations by default.

**Comment by tech-otaku** [comment]
Unfortunately it's not possible for the script to set the format of the menu bar clock to display the week number as it simply mimics what can otherwise be achieved by setting the format through System Preferences. It is therefore limited to the formats defined by Apple.

The 3rd party apps [itsycal](https://www.mowglii.com/itsycal/) and [Day-O](https://shauninman.com/archive/2016/10/20/day_o_2_mac_menu_bar_clock) can show the [week number](https://apple.stackexchange.com/questions/338620/show-current-calendar-week-in-menu-bar), but they both rely on showing an additional clock display in the menu bar. You can't choose not to display Apple's menu bar clock in Big Sur, but you could set it to analogue: _System Preferences_ > _Dock & Menu Bar_ > _Clock_.

I tried both of these apps. itsycal worked fine, but I couldn't display Day-O's preferences to be able to change the format. Looks as though the latter was last updated in 2016.

**Comment by bramchi** [comment]
Amazing, what you describe with the Day-O combo is exactly my quest and setup. :-) I've even reached out to the author of Day-O about that updating issue. 

Itsycal looks very promising. In combination with your script, it results in a satisfying menu bar layout.

Thanks for that tip and your great work with this script.

**Comment by bramchi** [comment]
Amazing, what you describe is exactly my setup and quest too :-) I've even reached out to the author about the updating issue.

Itsycal looks very promising. Together with your script it does result in a satisfying menu bar layout.

Thanks for the tip and your great work with this script!
